// <auto-generated />
using System;
using LIS_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LIS_API.Migrations
{
    [DbContext(typeof(LISContext))]
    [Migration("20240612035506_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LIS_API.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LIS_API.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("locationid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("productid")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("locationid");

                    b.HasIndex("productid");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("LIS_API.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userid");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("LIS_API.Models.Invoice_Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("invoiceId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("invoiceId");

                    b.HasIndex("userid");

                    b.ToTable("Invoice_Products");
                });

            modelBuilder.Entity("LIS_API.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("categoryid")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LIS_API.Models.StoreLocation", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("retailName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("retailSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shortname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("storeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("warehouseID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("StoreLocations");
                });

            modelBuilder.Entity("LIS_API.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LIS_API.Models.User_Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("storeLocationid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("storeLocationid");

                    b.HasIndex("userid");

                    b.ToTable("User_Locations");
                });

            modelBuilder.Entity("LIS_API.Models.Inventory", b =>
                {
                    b.HasOne("LIS_API.Models.StoreLocation", "location")
                        .WithMany()
                        .HasForeignKey("locationid");

                    b.HasOne("LIS_API.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("productid");

                    b.Navigation("location");

                    b.Navigation("product");
                });

            modelBuilder.Entity("LIS_API.Models.Invoice", b =>
                {
                    b.HasOne("LIS_API.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userid");

                    b.Navigation("user");
                });

            modelBuilder.Entity("LIS_API.Models.Invoice_Product", b =>
                {
                    b.HasOne("LIS_API.Models.Invoice", "invoice")
                        .WithMany()
                        .HasForeignKey("invoiceId");

                    b.HasOne("LIS_API.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userid");

                    b.Navigation("invoice");

                    b.Navigation("user");
                });

            modelBuilder.Entity("LIS_API.Models.Product", b =>
                {
                    b.HasOne("LIS_API.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.Navigation("category");
                });

            modelBuilder.Entity("LIS_API.Models.User_Location", b =>
                {
                    b.HasOne("LIS_API.Models.StoreLocation", "storeLocation")
                        .WithMany()
                        .HasForeignKey("storeLocationid");

                    b.HasOne("LIS_API.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userid");

                    b.Navigation("storeLocation");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
